name: Test

on: [ push ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.6
          architecture: x64
      - name: Instalar dependências
        run: |
          pip install -q pipenv 
          pip install codecov
          pipenv sync --dev
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true
      - name: Rodar Testes Automáticos
        run: |
          pytest --cov=libpythonpro
      

